source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'bcrypt'
gem 'newrelic_rpm'
gem 'redis'
gem 'expeditor'

group :development do
  gem 'sinatra-contrib'
end
